sudo: required
services:
  - docker

before_install:
  - docker build -t antonlebiodkin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run antonlebiodkin/react-test npm test -- --coverage

after_success:
  - docker build -t antonlebiodkin/multi-client ./client
  - docker build -t antonlebiodkin/multi-server ./server
  - docker build -t antonlebiodkin/multi-worker ./worker
  - docker build -t antonlebiodkin/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push antonlebiodkin/multi-client
  - docker push antonlebiodkin/multi-server
  - docker push antonlebiodkin/multi-worker
  - docker push antonlebiodkin/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-515953063039
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
